-- A.GRAY seed: categories, sample products, local placeholder media, homepage/nav buttons.
-- Run AFTER 001_schema.sql. Re-runnable: upserts by slug/key; media inserted only if product has none.

insert into public.categories (slug, name_ru, name_en, blurb_ru, sort_order, visible)
values
  ('rings', 'Кольца', 'Rings', 'Печатки, солитеры и повседневные формы.', 1, true),
  ('bracelets', 'Браслеты', 'Bracelets', 'Жёсткие и мягкие линии, ручная пайка.', 2, true),
  ('crosses', 'Кресты', 'Crosses', 'Православные и лаконичные нательные кресты.', 3, true),
  ('earrings', 'Серьги', 'Earrings', 'Капли, кольца и вечерние пары.', 4, true),
  ('pendants', 'Подвески', 'Pendants', 'Кулоны на цепь — символ, буква, камень.', 5, true),
  ('icons', 'Иконы', 'Icons', 'Нательные иконки, чеканка и эмаль.', 6, true),
  ('chains', 'Цепи', 'Chains', 'Бисмарк, якорь, box — разный характер звена.', 7, true),
  ('wedding', 'Обручальные', 'Wedding', 'Парные кольца: классика, сатин, comfort fit.', 8, true),
  ('sport', 'SPORT', 'Sport', 'Мужская спортивная линия: каучук, золото, геометрия.', 9, true),
  ('others', 'OTHERS', 'Others', 'Остальное: редкие формы, ремонт, вещи вне основных линий.', 10, true)
on conflict (slug) do update set
  name_ru = excluded.name_ru,
  name_en = excluded.name_en,
  blurb_ru = excluded.blurb_ru,
  sort_order = excluded.sort_order,
  visible = excluded.visible;

insert into public.products (
  category_id, slug, title_ru, description_ru, price_cents, currency,
  metal, assay, weight_g, size_label, sizes, sku, stone, lead_days, status, featured
)
values
  (
    (select id from public.categories where slug = 'rings'),
    'aurora',
    'Кольцо Aurora',
    'Солитер с тихой короной. Камень посажен низко, шинка мягко сужается к ладони — кольцо собрано для ежедневной носки, не только для витрины.',
    18600000,
    'RUB',
    'Золото жёлтое',
    '585',
    3.8,
    'Размер',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-R-0142',
    'Бриллиант 0.25 ct',
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'rings'),
    'solstice',
    'Кольцо Solstice',
    'Овальная оправа, сапфир глубокого тона. Боковые грани шинки отполированы в зеркало — свет скользит, не дробит форму.',
    12400000,
    'RUB',
    'Золото белое',
    '585',
    4.2,
    'Размер',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-R-0208',
    'Сапфир 0.40 ct',
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'rings'),
    'noir-signet',
    'Печатка Noir',
    'Мужская печатка с площадкой под монограмму. Внутренняя поверхность — comfort fit. Гравировка в ателье по запросу.',
    9800000,
    'RUB',
    'Золото жёлтое',
    '585',
    8.6,
    'Размер',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-R-0311',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'bracelets'),
    'linea',
    'Браслет Linea',
    'Жёсткий браслет с едва заметным замком. Линия непрерывная: золото читается как архитектура запястья, а не как декор.',
    14200000,
    'RUB',
    'Золото жёлтое',
    '585',
    12.4,
    'Обхват, см',
    '["17","18","19","20","21"]'::jsonb,
    'AG-B-1104',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'bracelets'),
    'venice',
    'Браслет Venice',
    'Мягкое плетение, звенья плотные, замок-коробка с предохранителем. Носится поверх манжеты и на голую руку.',
    7600000,
    'RUB',
    'Золото жёлтое',
    '585',
    9.1,
    'Обхват, см',
    '["17","18","19","20","21"]'::jsonb,
    'AG-B-1188',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'bracelets'),
    'cobra',
    'Браслет Cobra',
    'Плотное «кобра»-плетение, 750 проба. Тяжёлый ход по руке, глухой золотой цвет. Для тех, кто выбирает вес, а не блеск.',
    16800000,
    'RUB',
    'Золото жёлтое',
    '750',
    18.2,
    'Обхват, см',
    '["17","18","19","20","21"]'::jsonb,
    'AG-B-1210',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'crosses'),
    'orthodox-classic',
    'Крест Orthodox',
    'Православный нательный крест: косое подножие, титла, спокойный рельеф. Оборотная сторона — молитва. Цепь подбирается отдельно.',
    5400000,
    'RUB',
    'Золото жёлтое',
    '585',
    3.1,
    null,
    '[]'::jsonb,
    'AG-C-2041',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'crosses'),
    'cross-minimal',
    'Крест Minimal',
    'Латинский крест без декора. Тонкое сечение, матовая грань и полированный торец — крест читается в профиль.',
    3800000,
    'RUB',
    'Золото белое',
    '585',
    2.2,
    null,
    '[]'::jsonb,
    'AG-C-2099',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'crosses'),
    'cross-on-chain',
    'Крест на цепи',
    'Комплект: крест и якорная цепь 585. Узел соединения усилен. Готовый нательный набор без подбора «на глаз».',
    8900000,
    'RUB',
    'Золото жёлтое',
    '585',
    7.4,
    'Длина цепи, см',
    '["45","50","55","60","65"]'::jsonb,
    'AG-C-2217',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'earrings'),
    'drops',
    'Серьги Drops',
    'Капли с подвижным камнем. Английский замок. Пара собрана так, чтобы серьга падала вертикально и не разворачивалась.',
    11200000,
    'RUB',
    'Золото жёлтое',
    '585',
    5.6,
    null,
    '[]'::jsonb,
    'AG-E-3302',
    'Цитрин',
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'earrings'),
    'hoops',
    'Серьги Hoops',
    'Средние кольца, сечение — мягкий овал. Застёжка скрыта в дуге. Дневной формат, который держит вечер.',
    6400000,
    'RUB',
    'Золото жёлтое',
    '585',
    4.8,
    null,
    '[]'::jsonb,
    'AG-E-3375',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'earrings'),
    'stella',
    'Серьги Stella',
    'Небольшие звёзды с россыпью. Лёгкие, на каждый день, без театрального блеска — только точечный свет.',
    7900000,
    'RUB',
    'Золото белое',
    '585',
    3.9,
    null,
    '[]'::jsonb,
    'AG-E-3419',
    'Бриллиантовая крошка',
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'pendants'),
    'lune',
    'Подвеска Lune',
    'Лунный кулон на тонкой петле. Внутренняя плоскость сатинирована, внешний контур — полировка. Цепь в комплект не входит.',
    4700000,
    'RUB',
    'Золото жёлтое',
    '585',
    2.7,
    null,
    '[]'::jsonb,
    'AG-P-4501',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'pendants'),
    'coeur',
    'Подвеска Cœur',
    'Сердце без сентиментальной толщины: тонкий объём, закрытый каст. Можно носить на цепи 45 или 50 см.',
    5200000,
    'RUB',
    'Золото жёлтое',
    '585',
    3,
    null,
    '[]'::jsonb,
    'AG-P-4566',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'pendants'),
    'letter',
    'Подвеска Letter',
    'Буква на выбор — гравируется в ателье. Шрифт близкий к нашему логотипу. Заказ по артикулу с указанием литеры.',
    4100000,
    'RUB',
    'Золото жёлтое',
    '585',
    2.4,
    null,
    '[]'::jsonb,
    'AG-P-4612',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'icons'),
    'vladimir',
    'Икона Владимирская',
    'Нательная икона, чеканный оклад, лик закрыт стеклом. Оборот — тропарь. Носится на отдельной тонкой цепи.',
    6800000,
    'RUB',
    'Золото жёлтое',
    '585',
    6.2,
    null,
    '[]'::jsonb,
    'AG-I-5703',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'icons'),
    'angel',
    'Икона Ангел-хранитель',
    'Небольшой образок. Контур крыла выведен одной линией, без лишней насечки. Подходит как крестильный подарок.',
    5900000,
    'RUB',
    'Золото жёлтое',
    '585',
    5.1,
    null,
    '[]'::jsonb,
    'AG-I-5788',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'chains'),
    'bismarck',
    'Цепь Bismarck',
    'Классический бисмарк, плотное звено, замок-карабин с ответной коробкой. Вес указан для 55 см — другие длины пересчитываются в ателье.',
    21000000,
    'RUB',
    'Золото жёлтое',
    '585',
    28,
    'Длина, см',
    '["45","50","55","60","65"]'::jsonb,
    'AG-N-6804',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'chains'),
    'anchor',
    'Цепь Anchor',
    'Якорное плетение среднего звена. Хорошо держит крест и икону, не перекручивается на 50–55 см.',
    9600000,
    'RUB',
    'Золото жёлтое',
    '585',
    14.6,
    'Длина, см',
    '["45","50","55","60","65"]'::jsonb,
    'AG-N-6861',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'chains'),
    'box-chain',
    'Цепь Box',
    'Квадратное звено, белый металл. Для кулона: цепь остаётся геометрией, подвеска — акцентом.',
    7200000,
    'RUB',
    'Золото белое',
    '585',
    8.8,
    'Длина, см',
    '["45","50","55","60","65"]'::jsonb,
    'AG-N-6910',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'wedding'),
    'wedding-classic',
    'Обручальные Classic',
    'Парные кольца классического профиля, ширина 4 мм. Внутренняя гравировка даты и имён — в ателье. Цена за пару, вес суммарный ориентир.',
    15400000,
    'RUB',
    'Золото жёлтое',
    '585',
    8.4,
    'Размер (пара уточняется)',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-W-8001',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'wedding'),
    'wedding-satin',
    'Обручальные Satin',
    'Сатинированная дорожка и полированные рёбра. Можно собрать пару в одном металле или контрастом жёлтое + белое.',
    16800000,
    'RUB',
    'Золото жёлтое / белое',
    '585',
    9,
    'Размер (пара уточняется)',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-W-8044',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'wedding'),
    'wedding-comfort',
    'Обручальные Comfort',
    'Comfort fit, 750 проба, ширина 5 мм. Кольцо не режет при суточной носке. Рекомендуем примерку в ателье перед отливкой пары.',
    17600000,
    'RUB',
    'Золото жёлтое',
    '750',
    10.2,
    'Размер (пара уточняется)',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-W-8112',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'sport'),
    'pulse',
    'SPORT Pulse',
    'Каучуковый браслет с золотой вставкой. Замок скрытый. Линия SPORT — для зала и дороги, металл не на весь обхват.',
    6400000,
    'RUB',
    'Золото жёлтое / каучук',
    '585',
    6.5,
    'Размер',
    '["S","M","L"]'::jsonb,
    'AG-S-9007',
    null,
    14,
    'published',
    true
  ),
  (
    (select id from public.categories where slug = 'sport'),
    'track',
    'SPORT Track',
    'Геометрическая печатка SPORT: скошенная площадка, чёрное покрытие граней. Держит удар повседневной носки.',
    4800000,
    'RUB',
    'Золото жёлтое',
    '585',
    7.8,
    'Размер',
    '["15","15.5","16","16.5","17","17.5","18","18.5","19","20","21"]'::jsonb,
    'AG-S-9042',
    null,
    14,
    'published',
    false
  ),
  (
    (select id from public.categories where slug = 'sport'),
    'grip',
    'SPORT Grip',
    'Более широкий SPORT-браслет, золотая планка с винтовым креплением. Каучук заменяется в ателье.',
    7100000,
    'RUB',
    'Золото жёлтое / каучук',
    '585',
    8.1,
    'Размер',
    '["S","M","L"]'::jsonb,
    'AG-S-9090',
    null,
    14,
    'published',
    false
  )
on conflict (slug) do update set
  category_id = excluded.category_id,
  title_ru = excluded.title_ru,
  description_ru = excluded.description_ru,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  metal = excluded.metal,
  assay = excluded.assay,
  weight_g = excluded.weight_g,
  size_label = excluded.size_label,
  sizes = excluded.sizes,
  sku = excluded.sku,
  stone = excluded.stone,
  featured = excluded.featured;

insert into public.product_media (product_id, kind, url, sort_order, is_primary)
select x.product_id, x.kind::public.media_kind, x.url, x.sort_order, x.is_primary
from (values
  ((select id from public.products where sku = 'AG-R-0142'), 'photo', '/media/products/AG-R-0142/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-R-0142'), 'photo', '/media/products/AG-R-0142/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-R-0208'), 'photo', '/media/products/AG-R-0208/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-R-0208'), 'photo', '/media/products/AG-R-0208/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-R-0311'), 'photo', '/media/products/AG-R-0311/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-R-0311'), 'photo', '/media/products/AG-R-0311/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-B-1104'), 'photo', '/media/products/AG-B-1104/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-B-1104'), 'photo', '/media/products/AG-B-1104/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-B-1188'), 'photo', '/media/products/AG-B-1188/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-B-1188'), 'photo', '/media/products/AG-B-1188/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-B-1210'), 'photo', '/media/products/AG-B-1210/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-B-1210'), 'photo', '/media/products/AG-B-1210/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-C-2041'), 'photo', '/media/products/AG-C-2041/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-C-2041'), 'photo', '/media/products/AG-C-2041/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-C-2099'), 'photo', '/media/products/AG-C-2099/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-C-2099'), 'photo', '/media/products/AG-C-2099/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-C-2217'), 'photo', '/media/products/AG-C-2217/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-C-2217'), 'photo', '/media/products/AG-C-2217/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-E-3302'), 'photo', '/media/products/AG-E-3302/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-E-3302'), 'photo', '/media/products/AG-E-3302/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-E-3375'), 'photo', '/media/products/AG-E-3375/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-E-3375'), 'photo', '/media/products/AG-E-3375/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-E-3419'), 'photo', '/media/products/AG-E-3419/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-E-3419'), 'photo', '/media/products/AG-E-3419/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-P-4501'), 'photo', '/media/products/AG-P-4501/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-P-4501'), 'photo', '/media/products/AG-P-4501/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-P-4566'), 'photo', '/media/products/AG-P-4566/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-P-4566'), 'photo', '/media/products/AG-P-4566/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-P-4612'), 'photo', '/media/products/AG-P-4612/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-P-4612'), 'photo', '/media/products/AG-P-4612/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-I-5703'), 'photo', '/media/products/AG-I-5703/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-I-5703'), 'photo', '/media/products/AG-I-5703/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-I-5788'), 'photo', '/media/products/AG-I-5788/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-I-5788'), 'photo', '/media/products/AG-I-5788/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-N-6804'), 'photo', '/media/products/AG-N-6804/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-N-6804'), 'photo', '/media/products/AG-N-6804/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-N-6861'), 'photo', '/media/products/AG-N-6861/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-N-6861'), 'photo', '/media/products/AG-N-6861/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-N-6910'), 'photo', '/media/products/AG-N-6910/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-N-6910'), 'photo', '/media/products/AG-N-6910/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-W-8001'), 'photo', '/media/products/AG-W-8001/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-W-8001'), 'photo', '/media/products/AG-W-8001/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-W-8044'), 'photo', '/media/products/AG-W-8044/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-W-8044'), 'photo', '/media/products/AG-W-8044/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-W-8112'), 'photo', '/media/products/AG-W-8112/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-W-8112'), 'photo', '/media/products/AG-W-8112/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-S-9007'), 'photo', '/media/products/AG-S-9007/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-S-9007'), 'photo', '/media/products/AG-S-9007/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-S-9042'), 'photo', '/media/products/AG-S-9042/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-S-9042'), 'photo', '/media/products/AG-S-9042/02.svg', 2, false),
  ((select id from public.products where sku = 'AG-S-9090'), 'photo', '/media/products/AG-S-9090/01.svg', 1, true),
  ((select id from public.products where sku = 'AG-S-9090'), 'photo', '/media/products/AG-S-9090/02.svg', 2, false)
) as x(product_id, kind, url, sort_order, is_primary)
where not exists (
  select 1 from public.product_media pm where pm.product_id = x.product_id
);

insert into public.site_settings (key, label_ru, href, visible, sort_order, meta)
values
  ('nav.catalog', 'Каталог', '/catalog', true, 10, '{"group":"nav"}'::jsonb),
  ('nav.atelier', 'Ателье', '/atelier', true, 20, '{"group":"nav"}'::jsonb),
  ('home.cta_primary', 'Смотреть коллекцию', '/catalog', true, 10, '{"group":"home"}'::jsonb),
  ('home.cta_secondary', 'Ателье', '/atelier', true, 20, '{"group":"home"}'::jsonb),
  ('home.workshop_cta', 'Как попасть', '/atelier', true, 30, '{"group":"home"}'::jsonb)
on conflict (key) do update set
  label_ru = excluded.label_ru,
  href = excluded.href,
  visible = excluded.visible,
  sort_order = excluded.sort_order,
  meta = excluded.meta;
